FROM debian:bookworm-slim
COPY --from=denoland/deno:bin-2.3.3 /deno /usr/local/bin/deno

ENV DENO_INSTALL="/root/.deno"
ENV PATH="$DENO_INSTALL/bin:$PATH"

WORKDIR /app
# COPY . .

# CMD ["deno", "run", "--allow-net", "main.ts"]