FROM ghcr.io/u-na-gi/rust-node-deno-wasm-pack:latest

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

# Copy application files
COPY . .

# Cache the dependencies
RUN deno cache main.ts

# Expose the port
EXPOSE 3323

CMD ["deno", "run", "-A", "main.ts"]