name: Publish to JSR

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        deno-version: ["latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Run tests
        run: |
          cd scenario-flow
          deno test --coverage=coverage

      - name: Check formatting
        run: |
          cd scenario-flow
          deno fmt --check

      - name: Lint code
        run: |
          cd scenario-flow
          deno lint

      - name: Publish to JSR
        run: |
          cd scenario-flow
          npx jsr publish
